void main() {
  // 1 - Introdução a Variáveis ✅
  // 2 - Operadores ✅
  // 3 - Introdução null-safety ✅
  // 4 - IF e-SWITCH ✅
  // 5 - Estrutura de Repetição 📝
  // 6 - Metodos e Classes 📌
  // 7 - Future, Async e Await 📌
  // 8 - Orientação a objetos 📌
  // 9 - Herança, Polimorfismo e Abstração 📌
}
